#!/usr/bin/python
# ­*­ coding: utf­8 ­*­
# Nombre archivo: view_form.py
import sys
from PySide import QtGui, QtCore
from empleados import Ui_MainWindow
class Form(QtGui.QMainWindow):
	def __init__(self, parent=None):
		QtGui.QMainWindow.__init__(self, parent)
		self.ui =  Ui_MainWindow()
		self.ui.setupUi(self)
		#self.ui.crear.clicked.connect(self.create)
		#self.ui.cancelar.clicked.connect(self.cancel)
		
	def cancel(self):
		self.reject()

if __name__ == "__main__":
	app = QtGui.QApplication(sys.argv)
	main = Form()
	sys.exit(app.exec_())